// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/infrastructure/clients/proto/auth/grpc_message_handler.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7088bb675ecf2476, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	AccessToken           string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken          string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	AccessTokenExpiresAt  string   `protobuf:"bytes,3,opt,name=accessTokenExpiresAt,proto3" json:"accessTokenExpiresAt,omitempty"`
	RefreshTokenExpiresAt string   `protobuf:"bytes,4,opt,name=refreshTokenExpiresAt,proto3" json:"refreshTokenExpiresAt,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7088bb675ecf2476, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AuthResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *AuthResponse) GetAccessTokenExpiresAt() string {
	if m != nil {
		return m.AccessTokenExpiresAt
	}
	return ""
}

func (m *AuthResponse) GetRefreshTokenExpiresAt() string {
	if m != nil {
		return m.RefreshTokenExpiresAt
	}
	return ""
}

type RefreshRequest struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshRequest) Reset()         { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()    {}
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7088bb675ecf2476, []int{2}
}

func (m *RefreshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshRequest.Unmarshal(m, b)
}
func (m *RefreshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshRequest.Marshal(b, m, deterministic)
}
func (m *RefreshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshRequest.Merge(m, src)
}
func (m *RefreshRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshRequest.Size(m)
}
func (m *RefreshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshRequest proto.InternalMessageInfo

func (m *RefreshRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	AccessToken           string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken          string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	AccessTokenExpiresAt  string   `protobuf:"bytes,3,opt,name=accessTokenExpiresAt,proto3" json:"accessTokenExpiresAt,omitempty"`
	RefreshTokenExpiresAt string   `protobuf:"bytes,4,opt,name=refreshTokenExpiresAt,proto3" json:"refreshTokenExpiresAt,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *RefreshResponse) Reset()         { *m = RefreshResponse{} }
func (m *RefreshResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshResponse) ProtoMessage()    {}
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7088bb675ecf2476, []int{3}
}

func (m *RefreshResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshResponse.Unmarshal(m, b)
}
func (m *RefreshResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshResponse.Marshal(b, m, deterministic)
}
func (m *RefreshResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshResponse.Merge(m, src)
}
func (m *RefreshResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshResponse.Size(m)
}
func (m *RefreshResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshResponse proto.InternalMessageInfo

func (m *RefreshResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RefreshResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *RefreshResponse) GetAccessTokenExpiresAt() string {
	if m != nil {
		return m.AccessTokenExpiresAt
	}
	return ""
}

func (m *RefreshResponse) GetRefreshTokenExpiresAt() string {
	if m != nil {
		return m.RefreshTokenExpiresAt
	}
	return ""
}

type CheckTokenRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenRequest) Reset()         { *m = CheckTokenRequest{} }
func (m *CheckTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CheckTokenRequest) ProtoMessage()    {}
func (*CheckTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7088bb675ecf2476, []int{4}
}

func (m *CheckTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenRequest.Unmarshal(m, b)
}
func (m *CheckTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenRequest.Marshal(b, m, deterministic)
}
func (m *CheckTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenRequest.Merge(m, src)
}
func (m *CheckTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CheckTokenRequest.Size(m)
}
func (m *CheckTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenRequest proto.InternalMessageInfo

func (m *CheckTokenRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type CheckTokenResponse struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenResponse) Reset()         { *m = CheckTokenResponse{} }
func (m *CheckTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CheckTokenResponse) ProtoMessage()    {}
func (*CheckTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7088bb675ecf2476, []int{5}
}

func (m *CheckTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenResponse.Unmarshal(m, b)
}
func (m *CheckTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenResponse.Marshal(b, m, deterministic)
}
func (m *CheckTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenResponse.Merge(m, src)
}
func (m *CheckTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CheckTokenResponse.Size(m)
}
func (m *CheckTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenResponse proto.InternalMessageInfo

func (m *CheckTokenResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RegisterRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7088bb675ecf2476, []int{6}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7088bb675ecf2476, []int{7}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AuthRequest)(nil), "AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "AuthResponse")
	proto.RegisterType((*RefreshRequest)(nil), "RefreshRequest")
	proto.RegisterType((*RefreshResponse)(nil), "RefreshResponse")
	proto.RegisterType((*CheckTokenRequest)(nil), "CheckTokenRequest")
	proto.RegisterType((*CheckTokenResponse)(nil), "CheckTokenResponse")
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
}

func init() {
	proto.RegisterFile("internal/infrastructure/clients/proto/auth/grpc_message_handler.proto", fileDescriptor_7088bb675ecf2476)
}

var fileDescriptor_7088bb675ecf2476 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x53, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x95, 0xea, 0xef, 0xb1, 0x5b, 0xdb, 0x53, 0xb7, 0x18, 0x9d, 0xcc, 0x42, 0xa1, 0x87, 0xb2,
	0xa2, 0xae, 0x4b, 0x8f, 0xc5, 0x2d, 0xa6, 0xed, 0xa1, 0x17, 0xd1, 0x53, 0x73, 0x30, 0x8a, 0x3c,
	0x96, 0x84, 0x15, 0x49, 0xd9, 0x5d, 0x91, 0xfc, 0xba, 0x40, 0x7e, 0x45, 0xfe, 0x4e, 0xb0, 0xd6,
	0xb2, 0x65, 0xd9, 0x10, 0xc8, 0x2d, 0x27, 0x31, 0xf3, 0xe6, 0x3d, 0x66, 0x9e, 0xde, 0xc2, 0x22,
	0x8c, 0x15, 0x89, 0xd8, 0x8d, 0xec, 0x30, 0x5e, 0x0b, 0x57, 0x2a, 0x91, 0x79, 0x2a, 0x13, 0x64,
	0x7b, 0x51, 0x48, 0xb1, 0x92, 0x76, 0x2a, 0x12, 0x95, 0xd8, 0x6e, 0xa6, 0x02, 0xdb, 0x17, 0xa9,
	0xb7, 0xbc, 0x22, 0x29, 0x5d, 0x9f, 0x96, 0x81, 0x1b, 0xaf, 0x22, 0x12, 0x3c, 0xc7, 0xd9, 0x77,
	0xe8, 0xce, 0x33, 0x15, 0x38, 0x74, 0x9d, 0x91, 0x54, 0x38, 0x82, 0x46, 0x94, 0xf8, 0x61, 0x3c,
	0x36, 0x27, 0xe6, 0xc7, 0x8e, 0xa3, 0x0b, 0xb4, 0xa0, 0x9d, 0xba, 0x52, 0xde, 0x24, 0x62, 0x35,
	0x7e, 0x95, 0x03, 0xfb, 0x9a, 0xdd, 0x99, 0xd0, 0xd3, 0x0a, 0x32, 0x4d, 0x62, 0x49, 0x38, 0x81,
	0xae, 0xeb, 0x79, 0x24, 0xe5, 0xbf, 0x64, 0x43, 0x85, 0x50, 0xb9, 0x85, 0x0c, 0x7a, 0x82, 0xd6,
	0x82, 0x64, 0xa0, 0x47, 0xb4, 0xe4, 0x51, 0x0f, 0xa7, 0x30, 0x2a, 0x51, 0x16, 0xb7, 0x69, 0x28,
	0x48, 0xce, 0xd5, 0xb8, 0x96, 0xcf, 0x9e, 0xc5, 0x70, 0x06, 0xef, 0xca, 0x1a, 0x07, 0x52, 0x3d,
	0x27, 0x9d, 0x07, 0xd9, 0x0c, 0xde, 0x38, 0x1a, 0x28, 0x4c, 0xa8, 0xee, 0x67, 0x9e, 0xee, 0xc7,
	0xee, 0x4d, 0xe8, 0xef, 0x69, 0x2f, 0xf4, 0xf2, 0xaf, 0x30, 0xfc, 0x19, 0x90, 0xb7, 0xc9, 0xdb,
	0xc5, 0xf1, 0x4f, 0x1e, 0xc1, 0x3e, 0x01, 0x96, 0x69, 0xbb, 0xe3, 0xdf, 0x43, 0x33, 0x93, 0x24,
	0xfe, 0xac, 0x72, 0x4a, 0xc3, 0xd9, 0x55, 0xec, 0x62, 0xeb, 0x93, 0x1f, 0x4a, 0x45, 0xe2, 0xd9,
	0x21, 0x2b, 0x89, 0xd7, 0x8e, 0xc4, 0x11, 0x06, 0x07, 0x71, 0xbd, 0xc8, 0xf4, 0xc1, 0x04, 0xfc,
	0x25, 0x52, 0xef, 0xaf, 0xce, 0xfb, 0x6f, 0x1d, 0x77, 0xfc, 0x0c, 0xed, 0x62, 0x14, 0x07, 0xbc,
	0xb2, 0x92, 0x35, 0xe4, 0x55, 0x1d, 0x66, 0xe0, 0x07, 0xa8, 0x6f, 0x93, 0x8d, 0x3d, 0x5e, 0x7a,
	0x22, 0xd6, 0x6b, 0x5e, 0x8e, 0x3b, 0x33, 0x90, 0x43, 0x6b, 0x97, 0x04, 0xec, 0xf3, 0xe3, 0x28,
	0x59, 0x03, 0x5e, 0x09, 0x09, 0x33, 0xf0, 0x1b, 0xc0, 0xc1, 0x3f, 0x44, 0x7e, 0xf2, 0x0f, 0xac,
	0xb7, 0xfc, 0xd4, 0x60, 0x66, 0xfc, 0xe8, 0xfc, 0x6f, 0x71, 0xfd, 0xac, 0x2f, 0x9b, 0xf9, 0xe7,
	0xcb, 0x63, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0x2f, 0x95, 0x96, 0x06, 0x04, 0x00, 0x00,
}
